credentials: &credentials
  encoding: utf8
  adapter: postgresql
  username: mail_manager
  password: mail_manager_pass
  host: localhost
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *credentials 
  database: mail_manager_development
 
test:
  <<: *credentials 
  database: mail_manager_test
 
production:
  <<: *credentials 
  database: mail_manager
